services:
  app: 
    image: bennedistus/forge_flows_front:v1
    volumes:
      - ./:/app
    container_name: forge_flows_front
    ports:
      - "3000:80" # Expose Nginx internal (port 80) ke port 3000 VPS kamu
    restart: unless-stopped
